### ISSUE TITLE
onConfigurationReceived called multiple times upon connecting

### ISSUE THREAD

**Issue by tyczj** [androidthings/cloud-iot-core-androidthings#1]
Is this the expected behavior that onConfigurationChanged gets called multiple times (twice from my testing) when you first connect to the mqtt server?

I know you are suppose to get the current configuration when you connect to IoT core but I always get it twice right in a row. After the initial 2x call I get them only when they change the configuration like I should. 

Possible bug?

**Comment by blakelawson** [comment]
Hi tyczj,

Thanks for bringing this up! I also observed this behavior when testing the library. I agree that it looks a little suspicious, but the duplicate device configuration messages originate from Cloud IoT Core. Since IotCoreClient.java subscribes to the Cloud IoT Core device configuration topic with MQTT QOS 1 (at least once), receiving duplicate device configuration is expected.

Hope that helps!

-Blake
